
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/samitkumarpatel-work/config-repo.git
        #uri: file:///path/to/the/repo/config-server/config-repo
  application:
    name: config-server


server:
  port: 8888

