spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          searchLocations: file://${CONFIG_FILE_LOCATION:/var/config}
        git:
          uri: https://github.com/samitkumarpatel-work/config-repo.git
  application:
    name: config-server

server:
  port: 8888

